export const BROKERS = [
    "Manual",
    "Exness", 
    "Deriv",
    "XM",
    "Pepperstone",
    "HFM",
    "IC Markets", 
    "FTMO", 
    "FundedNext",
    "OANDA", 
    "OctaFX",
    "FXTM",
    "FBS",
    "Admiral Markets",
    "IG",
    "Saxo Bank",
    "Interactive Brokers",
    "Axi",
    "FP Markets",
    "ThinkMarkets",
    "MetaQuotes", 
    "TopStep",
    "Other (Not Listed)"
];
